import Images from 'assets/images';
import SIZES, {scale, verticalScale} from 'constants/sizes';
import {APP_ROUTES} from 'navigation/routes';

const itemBackColor = '#313131';

const isIPad = SIZES.width > 400;

export const AnimatedDate = [
  {
    subtitle: 'DAO Password',
    itemIcon: Images.MainItmes.daoPassword,
    size: 3,
    itemTitle: 'DAO Password',
    isNew: false,
    color: itemBackColor,
    order: 78,
    xLine: scale(230),
    yLine: verticalScale(isIPad ? 55 : 45),
    navigationPath: APP_ROUTES.dao_password,
  },
  {
    subtitle: 'Marketplase',
    itemIcon: Images.MainItmes.packet2,
    size: 3,
    itemTitle: 'Marketplase',
    isNew: false,
    color: itemBackColor,
    order: 26,
    xLine: scale(380),
    yLine: verticalScale(isIPad ? 125 : 100),
    navigationPath: APP_ROUTES.marketplace,
  },
  {
    subtitle: 'Electronic',
    itemIcon: Images.MainItmes.ihead3,
    size: 3,
    itemTitle: 'Electronic',
    isNew: false,
    color: itemBackColor,
    order: 10,
    xLine: scale(75),
    yLine: verticalScale(isIPad ? 120 : 100),
  },
  {
    subtitle: 'Activitys',
    itemIcon: Images.MainItmes.activitiesImage,
    size: 2,
    itemTitle: 'Activitys',
    isNew: false,
    color: itemBackColor,
    order: 3,
    xLine: scale(isIPad ? 390 : 375),
    yLine: verticalScale(isIPad ? 55 : 45),
    navigationPath: APP_ROUTES.activities,
  },
  {
    subtitle: 'Marketplase',
    itemIcon: Images.MainItmes.packet2,
    size: 2,
    itemTitle: 'Marketplase',
    isNew: false,
    color: itemBackColor,
    order: 4,
    xLine: scale(isIPad ? 475 : 485),
    yLine: verticalScale(isIPad ? 0 : 5),
    navigationPath: APP_ROUTES.marketplace,
  },

  {
    subtitle: 'Voting',
    itemIcon: Images.MainItmes.likeImg,
    size: 2,
    itemTitle: 'Voting',
    isNew: false,
    color: itemBackColor,
    order: 6,
    xLine: scale(isIPad ? 560 : 590),
    yLine: verticalScale(isIPad ? 50 : 50),
  },

  {
    subtitle: 'NFT',
    itemIcon: Images.MainItmes.ring2,
    size: 2,
    itemTitle: 'NFT',
    isNew: false,
    color: itemBackColor,
    order: 8,
    xLine: scale(isIPad ? 550 : 580),
    yLine: verticalScale(isIPad ? 230 : 200),
  },

  {
    subtitle: 'Wallet',
    itemIcon: Images.MainItmes.wallet,
    size: 2,
    itemTitle: 'Wallet',
    isNew: false,
    order: 13,
    xLine: scale(isIPad ? 410 : 390),
    yLine: verticalScale(isIPad ? 230 : 200),
  },
  {
    subtitle: 'Tasks',
    itemIcon: Images.MainItmes.tasks3,
    size: 1,
    itemTitle: 'Tasks',
    isNew: false,
    color: itemBackColor,
    order: 5,
    xLine: scale(isIPad ? 200 : 185),
    yLine: verticalScale(isIPad ? 80 : 65),
  },
  {
    subtitle: 'Grades',
    itemIcon: Images.MainItmes.grades1,
    size: 1,
    itemTitle: 'Grades',
    isNew: false,
    color: itemBackColor,
    order: 7,
    xLine: scale(isIPad ? 290 : 305),
    yLine: verticalScale(isIPad ? 80 : 65),
  },
  {
    subtitle: 'Grades',
    itemIcon: Images.MainItmes.grades1,
    size: 1,
    itemTitle: 'Grades',
    isNew: false,
    color: itemBackColor,
    order: 99,
    xLine: scale(isIPad ? 245 : 245),
    yLine: verticalScale(isIPad ? 135 : 110),
  },
];
